version: 2
jobs:
  build:
    # AMD: this enables DLC (fails build)
    machine:
      image: ubuntu-1604:201903-01  # any available image
      docker_layer_caching: true
    # AMD: this enables Large resource
    # parallelism: 13
    # resource_class: medium
    # docker:
      # - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 tests.py
      - store_artifacts:
          path: test-reports/
          destination: amd

